pipeline {
   agent any
   
   environment {
       ABOUT='Run Script'
   }

   stages {
      stage('stage-1') {
         steps {
            echo "$ABOUT: This is build number $BUILD_NUMBER ."
            sh '''               
               chmod +x testScript.sh
               ./testScript.sh
            '''
         }
      }
   }
}
