pipeline {
    agent any
    environment {
        RELEASE='16.11.1987'
    }
    stages {
        stage('Build') {
            agent any
            environment {
                AUTHOR='Mohit-Dahiya'
            }
            steps {
                echo "Build Succeed. Release : ${RELEASE}, Author: ${AUTHOR}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing build ${RELEASE}..."
            }
        }
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'SIT', description: 'SIT environment')
                }
            }
            steps {
                script {
                    if (${TARGET_ENVIRONMENT == 'SIT')
                    {
                        echo 'Deploying build to SIT'
                    } else {
                        echo 'Deploying build to Dev'
                    }
                }
            }
        }        
    }
    post{
        always {
             echo 'Prints whether deploy happened or not, success or failure'
        }
    }
}
