pipeline {
   agent any
    environment {
      RELEASE='16.11.1987'
    }
   stages {
      stage('Build') {
            environment {
               LOG_LEVEL='INFO'
            }
            steps {
               echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
               sh 'chmod +x Builds/useSecret_build.sh'
               withCredentials([string(credentialsId: 'sam-name', variable: 'API_KEY')]) {
                  sh '''
                     ./Builds/useSecret_build.sh
                  '''
               }
            }
        }
        stage('Test') {
            steps {
               echo "Testing release ${RELEASE}"
               script {
                  if (Math.random() > 0.5) {
                     throw new Exception()
                  }
               }
               writeFile file: 'test-results.txt', text: 'passed'               
            }
        }
   }
   post {
      success {
         archiveArtifacts 'test-results.txt'
         echo 'Build is succedd!!'        
      }
      failure {
         echo 'Build is failed :('
      }
   }
}
